DROP DATABASE IF EXISTS `superdb`; 
CREATE DATABASE superdb CHARACTER 
SET utf8mb4 COLLATE utf8mb4_unicode_ci; 
USE superdb; 
DROP TABLE IF EXISTS `tb_example`; 
CREATE TABLE `tb_example` (`id` INT (11) NOT NULL AUTO_INCREMENT,`name` VARCHAR (255) NOT NULL DEFAULT '',PRIMARY KEY (`id`)) ENGINE=INNODB DEFAULT CHARSET=utf8mb4; 
SET FOREIGN_KEY_CHECKS=1;